name: yolov4-gpu

dependencies:
  - python==3.7.10
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.3.0rc0
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
    - mediapipe
    - openpyxl
    - pandas
    - -f https://download.pytorch.org/whl/torch_stable.html
    - torch==1.7.1+cu101
    - torchvision==0.8.2+cu101
    - torchaudio==0.7.2
